### ISSUE TITLE
Unable Load model using windows API booga_api_url 

### ISSUE THREAD

**Issue by PsychoSmiley** [Nuggt-dev/Nuggt#11]
[steps](https://github.com/Nuggt-dev/Nuggt/blob/main/nuggt-wizcoder/guide.md#installation) i done:
```
git clone https://github.com/Nuggt-dev/Nuggt.git
cd Nuggt
pip install -r requirements.txt
cd nuggt-wizcoder
```
Base api is not ssl so I enable extension `share` and `openai` in oobabooga/text-generation-webui to get a url close to the example and copy the url OPENAI_API_BASE=`https://example-Nuggt.trycloudflare.com/v1` to `booga_api_url` in `server.py`
```
set SERVER_TYPE=api
python server.py
```
after it never end load the model:
```
Server listening on 0.0.0.0:8081
Loading Model...
```

**Comment by shoibloya** [comment]
Hi there, so sorry for the late reply I just saw this, are you still having troubles using the api version?

**Comment by PsychoSmiley** [comment]
Yes, indeed, and when I try to use the local model, start from `set SERVER_TYPE=local`:
```
git lfs install
git clone https://huggingface.co/TheBloke/WizardCoder-15B-1.0-GPTQ
```
i did change torch for my version of cuda:
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 --force-reinstall`

it correctly pass the model load:
```
python server.py
streamlit run nuggt.py
``` 
and set up all the necessary APIs keys, including both with and without a dummy of OpenAI key.
`server.py` did receive the client call
```
Server listening on 0.0.0.0:8081
Loading Model...
CUDA extension not installed.
The safetensors archive passed at WizardCoder-15B-1.0-GPTQ\gptq_model-4bit-128g.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` method. Defaulting to 'pt' metadata.
GPTBigCodeGPTQForCausalLM hasn't fused attention module yet, will skip inject fused attention.
GPTBigCodeGPTQForCausalLM hasn't fused mlp module yet, will skip inject fused mlp.
Model Loaded
Client connected: ('127.0.0.1', 51484)
```
,but all I got on the console from `nuggt.py` is how to format my prompt, that i already done so.
[Instruction](https://github.com/Nuggt-dev/Nuggt/blob/5f308f40299c207f27fb364594d0157b5f29ebb8/nuggt-wizcoder/guide.md#tool-integration): `create using {tool:python} a snake game`, Output format: `I have saved a snake game`
```
Coming in...
[WinError 10054] An existing connection was forcibly closed by the remote host
```

**Comment by shoibloya** [comment]
Thank you for reporting. I have made changes to server.py to fix this issue! It should work fine now. 

For the API version, we only support the https non streaming version.. so make sure to use the --no-stream flag when configuring Oobabooga. 

PS: Do take note that for the api version the console will only print "Server listening on 0.0.0.0:8081" ("Model Loaded" is only for the local version).

**Comment by PsychoSmiley** [comment]
Same behavior for local model and for API version (include --no-stream), `python server.py` `Server listening on 0.0.0.0:8082`, Submit does show on UI `I am still working on it....` than log `[WinError 10061] No connection could be made because the target machine actively refused it`.

**Comment by shoibloya** [comment]
Can you share a bit more about your setup. Are you running the server and client on the same machine? 

Also, could you share more on how you configured the client.py host and port.
